#!/usr/bin/env bash
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. "$WM_PROJECT_DIR/bin/tools/RunFunctions"

# Restore the initial fields
rm -rf 0
cp -r 0.org 0

# Generate the refined LES mesh on the 10-way meshing decomposition
runApplication blockMesh
runApplication -s meshDecompose decomposePar \
    -decomposeParDict system/decomposeParDict.snappy
runParallel -s mesh -np 10 snappyHexMesh -overwrite
runApplication -s meshReconstruct reconstructParMesh -constant
rm -rf processor*

runApplication topoSet

if [ "$1" = "-parallel" ]
then
    runApplication -s flowDecompose decomposePar
    runParallel "$(getApplication)"
else
    runApplication "$(getApplication)"
fi
